[package]
name = "ion"
version = "0.8.4"
description = "parse and process ion files"
license = "MIT"
homepage = "http://github.com/pzol/ion_rs"
repository = "http://github.com/pzol/ion_rs"
authors = ["Piotr Zolnierek <pzolnierek@gmail.com>"]
